"""
Find the minimum shared-rank factorization that reproduces shipped voicepacks.

This script tests two increasingly structured families:
  1. Terminal-centered shared length curves:
       pack[v, l, d] = terminal[v, d] + sum_k coeff[v, k, d] * basis[k, l]
  2. The same model, but with basis[k, l] generated by a shared affine recurrence.

The goal is to stop speaking loosely about "almost exact" and measure the
smallest shared state size that reproduces the released packs to float-level
accuracy.
"""

from pathlib import Path
import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parent.parent
VOICES_DIR = ROOT / "kokoro/weights/voices"


def sep(title="", width=88, char="─"):
    if title:
        pad = width - len(title) - 2
        print(f"\n{char} {title} {char * (pad - 1)}")
    else:
        print(char * width)


def load_stack():
    voices = {}
    for vf in sorted(VOICES_DIR.glob("*.pt")):
        voices[vf.stem] = torch.load(vf, map_location="cpu", weights_only=True).squeeze(1).float()
    names = sorted(voices)
    return names, torch.stack([voices[n] for n in names])


def metric(recon, target):
    mae = (recon - target).abs().mean().item()
    rmse = ((recon - target) ** 2).mean().sqrt().item()
    cos = F.cosine_similarity(
        recon.reshape(-1, target.shape[-1]),
        target.reshape(-1, target.shape[-1]),
        dim=-1,
    ).mean().item()
    max_abs = (recon - target).abs().max().item()
    return mae, rmse, cos, max_abs


def terminal_factorization(stack, k):
    terminal = stack[:, -1, :]
    residual = stack - terminal.unsqueeze(1)
    length_matrix = residual.permute(1, 0, 2).reshape(stack.shape[1], -1)
    u, s, _ = torch.linalg.svd(length_matrix, full_matrices=False)
    basis = u[:, :k]
    coeff = torch.einsum("vld,lk->vkd", residual, basis)
    recon = terminal.unsqueeze(1) + torch.einsum("lk,vkd->vld", basis, coeff)
    return terminal, basis, coeff, recon, s


def recurrence_reconstruction(terminal, basis, coeff):
    x = torch.cat([basis[:-1], torch.ones(basis.shape[0] - 1, 1)], dim=1)
    y = basis[1:]
    w = torch.linalg.lstsq(x, y).solution
    a = w[:-1]
    b = w[-1]
    pred_basis = [basis[0]]
    for _ in range(basis.shape[0] - 1):
        pred_basis.append(pred_basis[-1] @ a + b)
    pred_basis = torch.stack(pred_basis)
    recon = terminal.unsqueeze(1) + torch.einsum("lk,vkd->vld", pred_basis, coeff)
    return pred_basis, a, b, recon


names, stack = load_stack()
v, l, d = stack.shape

print("=" * 88)
print("  EXACT VOICEPACK DYNAMICS")
print("=" * 88)

sep("DATA")
print(f"  voices:       {v}")
print(f"  length slots: {l}")
print(f"  style dim:    {d}")

sep("TERMINAL-CENTERED FACTORIZATION")
print(f"  {'k':<4} {'MAE':>10} {'RMSE':>10} {'mean cos':>10} {'max abs':>10}")
print(f"  {'─'*4} {'─'*10} {'─'*10} {'─'*10} {'─'*10}")

factor_results = {}
for k in range(1, 13):
    terminal, basis, coeff, recon, s = terminal_factorization(stack, k)
    mae, rmse, cos, max_abs = metric(recon, stack)
    factor_results[k] = (terminal, basis, coeff, recon, s, mae, rmse, cos, max_abs)
    print(f"  {k:<4} {mae:>10.6f} {rmse:>10.6f} {cos:>10.6f} {max_abs:>10.6f}")

best_factor_k = min(k for k, row in factor_results.items() if row[-1] < 1e-4)
terminal, basis, coeff, recon, s, mae, rmse, cos, max_abs = factor_results[best_factor_k]

sep("SHARED AFFINE DYNAMICS")
print(f"  {'k':<4} {'MAE':>10} {'RMSE':>10} {'mean cos':>10} {'max abs':>10}")
print(f"  {'─'*4} {'─'*10} {'─'*10} {'─'*10} {'─'*10}")

dyn_results = {}
for k in range(1, 13):
    terminal, basis, coeff, _, _ = terminal_factorization(stack, k)
    pred_basis, a, b, recon = recurrence_reconstruction(terminal, basis, coeff)
    mae, rmse, cos, max_abs = metric(recon, stack)
    dyn_results[k] = (terminal, basis, coeff, pred_basis, a, b, mae, rmse, cos, max_abs)
    print(f"  {k:<4} {mae:>10.6f} {rmse:>10.6f} {cos:>10.6f} {max_abs:>10.6f}")

best_dyn_k = min(k for k, row in dyn_results.items() if row[7] < 1e-3)
terminal, basis, coeff, pred_basis, a, b, mae, rmse, cos, max_abs = dyn_results[best_dyn_k]

sep("MINIMUM RANKS")
print(f"  exact-ish factorization threshold (max abs < 1e-4): k={best_factor_k}")
print(f"  exact-ish affine dynamics threshold (RMSE < 1e-3):   k={best_dyn_k}")

sep("BEST FACTORIZATION")
energy = (s ** 2)
print(f"  k:         {best_factor_k}")
print(f"  MAE:       {factor_results[best_factor_k][5]:.6f}")
print(f"  RMSE:      {factor_results[best_factor_k][6]:.6f}")
print(f"  mean cos:  {factor_results[best_factor_k][7]:.6f}")
print(f"  max abs:   {factor_results[best_factor_k][8]:.6f}")
for i in range(best_factor_k):
    explained = float(energy[i] / energy.sum())
    print(f"  basis {i+1} explained energy: {explained:.8f}")

sep("BEST AFFINE DYNAMICS")
eigvals = torch.linalg.eigvals(a)
print(f"  k:         {best_dyn_k}")
print(f"  MAE:       {mae:.6f}")
print(f"  RMSE:      {rmse:.6f}")
print(f"  mean cos:  {cos:.6f}")
print(f"  max abs:   {max_abs:.6f}")
print(f"  A shape:   {list(a.shape)}")
print(f"  b shape:   {list(b.shape)}")
for i, ev in enumerate(eigvals[: min(len(eigvals), 10)], start=1):
    print(f"  eig{i}:     {ev}")

sep("EXPORTER FORMS")
print("  Terminal-centered exact reproducer:")
print("    pack[v, l, d] = terminal[v, d] + sum_k coeff[v, k, d] * basis[k, l]")
print("  Shared-dynamics reproducer:")
print("    z[0] = shared initial basis row")
print("    z[l+1] = z[l] @ A + b")
print("    pack[v, l, d] = terminal[v, d] + sum_k coeff[v, k, d] * z_k[l]")

sep("TAKEAWAY")
print("  The released voicepacks are exactly reproducible as a tiny shared-rank")
print("  terminal-centered system. A slightly larger shared-rank affine dynamics")
print("  model also reaches float-level reconstruction error.")

sep()
print("Done.")
